[![npm](https://img.shields.io/npm/v/kronos-interceptor-line-header.svg)](https://www.npmjs.com/package/kronos-interceptor-line-header)
[![Greenkeeper](https://badges.greenkeeper.io/Kronos-Integration/kronos-interceptor-line-header.svg)](https://greenkeeper.io/)
[![semantic-release](https://img.shields.io/badge/%20%20%F0%9F%93%A6%F0%9F%9A%80-semantic--release-e10079.svg)](https://github.com/Kronos-Integration/kronos-interceptor-line-header)
[![Build Status](https://secure.travis-ci.org/Kronos-Integration/kronos-interceptor-line-header.png)](http://travis-ci.org/Kronos-Integration/kronos-interceptor-line-header)
[![bithound](https://www.bithound.io/github/Kronos-Integration/kronos-interceptor-line-header/badges/score.svg)](https://www.bithound.io/github/Kronos-Integration/kronos-interceptor-line-header)
[![codecov.io](http://codecov.io/github/Kronos-Integration/kronos-interceptor-line-header/coverage.svg?branch=master)](http://codecov.io/github/Kronos-Integration/kronos-interceptor-line-header?branch=master)
[![Coverage Status](https://coveralls.io/repos/Kronos-Integration/kronos-interceptor-line-header/badge.svg)](https://coveralls.io/r/Kronos-Integration/kronos-interceptor-line-header)
[![Code Climate](https://codeclimate.com/github/Kronos-Integration/kronos-interceptor-line-header/badges/gpa.svg)](https://codeclimate.com/github/Kronos-Integration/kronos-interceptor-line-header)
[![Known Vulnerabilities](https://snyk.io/test/github/Kronos-Integration/kronos-interceptor-line-header/badge.svg)](https://snyk.io/test/github/Kronos-Integration/kronos-interceptor-line-header)
[![GitHub Issues](https://img.shields.io/github/issues/Kronos-Integration/kronos-interceptor-line-header.svg?style=flat-square)](https://github.com/Kronos-Integration/kronos-interceptor-line-header/issues)
[![Stories in Ready](https://badge.waffle.io/Kronos-Integration/kronos-interceptor-line-header.svg?label=ready&title=Ready)](http://waffle.io/Kronos-Integration/kronos-interceptor-line-header)
[![Dependency Status](https://david-dm.org/Kronos-Integration/kronos-interceptor-line-header.svg)](https://david-dm.org/Kronos-Integration/kronos-interceptor-line-header)
[![devDependency Status](https://david-dm.org/Kronos-Integration/kronos-interceptor-line-header/dev-status.svg)](https://david-dm.org/Kronos-Integration/kronos-interceptor-line-header#info=devDependencies)
[![docs](http://inch-ci.org/github/Kronos-Integration/kronos-interceptor-line-header.svg?branch=master)](http://inch-ci.org/github/Kronos-Integration/kronos-interceptor-line-header)
[![downloads](http://img.shields.io/npm/dm/kronos-interceptor-line-header.svg?style=flat-square)](https://npmjs.org/package/kronos-interceptor-line-header)
[![Commitizen friendly](https://img.shields.io/badge/commitizen-friendly-brightgreen.svg)](http://commitizen.github.io/cz-cli/)

